# Generated by Django 3.1.7 on 2021-03-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20210331_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='day',
        ),
        migrations.CreateModel(
            name='MedicineDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
    ]
