# Generated by Django 3.1.7 on 2021-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20210331_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='time',
            field=models.CharField(max_length=32),
        ),
    ]
